question_data = [
    {"question": "The Earth is flat.", "correct_answer": "False", "true_answer": "False"},
    {"question": "Water boils at 100 degrees Celsius at sea level.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The capital of France is Paris.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The atomic number of oxygen is 8.", "correct_answer": "False", "true_answer": "8"},
    {"question": "Mount Everest is the tallest mountain on Earth.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The Great Wall of China is visible from space.", "correct_answer": "False", "true_answer": "False"},
    {"question": "The currency of Japan is the yen.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The Amazon River is the longest river in the world.", "correct_answer": "False",
     "true_answer": "False"},
    {"question": "Photosynthesis is the process by which plants convert light energy into chemical energy.",
     "correct_answer": "True", "true_answer": "True"},
    {"question": "Humans have five senses.", "correct_answer": "False", "true_answer": "More than five"},
    {"question": "The mitochondria is the powerhouse of the cell.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The boiling point of water decreases with altitude.", "correct_answer": "True",
     "true_answer": "True"},
    {"question": "Albert Einstein discovered the theory of relativity.", "correct_answer": "True",
     "true_answer": "True"},
    {"question": "Mars is known as the Red Planet.", "correct_answer": "True", "true_answer": "True"},
    {"question": "Oxygen is the most abundant element in the Earth's atmosphere.", "correct_answer": "False",
     "true_answer": "Nitrogen"},
    {"question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the sum of the "
                 "squares of the other two sides.",
     "correct_answer": "True", "true_answer": "True"},
    {"question": "Gold is a transition metal.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The speed of light is approximately 299,792,458 meters per second.", "correct_answer": "True",
     "true_answer": "299,792,458 m/s"},
    {"question": "The capital of Australia is Sydney.", "correct_answer": "False", "true_answer": "Canberra"},
    {"question": "The process of rusting is an example of oxidation.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The human body has 206 bones.", "correct_answer": "False", "true_answer": "More than 206"},
    {"question": "The longest river in Europe is the Danube.", "correct_answer": "False", "true_answer": "Volga"},
    {"question": "The chemical symbol for silver is Si.", "correct_answer": "False", "true_answer": "Ag"},
    {"question": "Antarctica is the coldest continent on Earth.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The speed of sound is faster in water than in air.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The Earth orbits the Sun.", "correct_answer": "True", "true_answer": "True"},
    {"question": "Copper is a noble metal.", "correct_answer": "False", "true_answer": "False"},
    {"question": "A concave lens diverges light rays.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The human body's largest organ is the skin.", "correct_answer": "True", "true_answer": "True"},
    {"question": "Sodium chloride is commonly known as table salt.", "correct_answer": "True", "true_answer": "True"},
    {"question": "A light-year is a unit of time.", "correct_answer": "False", "true_answer": "False"},
    {"question": "A nanometer is larger than a micrometer.", "correct_answer": "False", "true_answer": "False"},
    {"question": "The moon orbits the Earth.", "correct_answer": "True", "true_answer": "True"},
    {"question": "Nitrogen makes up the majority of Earth's atmosphere.", "correct_answer": "True",
     "true_answer": "True"},
    {"question": "The speed of a falling object increases as it gains altitude.", "correct_answer": "False",
     "true_answer": "False"},
    {"question": "The human body has four chambers in the heart.", "correct_answer": "False",
     "true_answer": "More than four"},
    {"question": "The chemical symbol for iron is Fe.", "correct_answer": "True", "true_answer": "Fe"},
    {"question": "Pluto is classified as a terrestrial planet.", "correct_answer": "False",
     "true_answer": "Dwarf planet"},
    {"question": "A light wave is an example of a transverse wave.", "correct_answer": "True", "true_answer": "True"},
    {"question": "A vertebrate is an animal with a backbone.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "correct_answer": "True", "true_answer": "True"},
    {"question": "Alfred Nobel invented dynamite.", "correct_answer": "True", "true_answer": "True"},
    {"question": "The boiling point of water is higher at lower altitudes.", "correct_answer": "True",
     "true_answer": "True"},
    {"question": "The human body has three pairs of salivary glands.", "correct_answer": "True", "true_answer": "True"},
    {"question": "Helium is the second most abundant element in the universe.", "correct_answer": "True",
     "true_answer": "True"},
    {"question": "A light wave travels faster than a sound wave.", "correct_answer": "True", "true_answer": "True"},
    {"question": "Jupiter is the largest planet in the solar system.", "correct_answer": "True", "true_answer": "True"}

]
